"""m1 persistence foundation

Revision ID: 0001
Revises:
Create Date: 2026-09-07 13:34:35.369157
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS control")
    op.execute("CREATE SCHEMA IF NOT EXISTS event_store")
    op.execute("CREATE SCHEMA IF NOT EXISTS langgraph")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configurations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("current_revision_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configurations")),
        sa.UniqueConstraint("kind", "key", name="uq_configurations_kind_key"),
        schema="control",
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=120), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('started','completed','failed')", name=op.f("ck_idempotency_records_state")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_records")),
        sa.UniqueConstraint("scope", "key", name="uq_idempotency_scope_key"),
        schema="control",
    )
    op.create_table(
        "orchestrator_instances",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("draining", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orchestrator_instances")),
        schema="control",
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint("status IN ('active', 'archived')", name=op.f("ck_projects_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("slug", name=op.f("uq_projects_slug")),
        schema="control",
    )
    op.create_table(
        "workflow_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("current_published_version_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_templates")),
        sa.UniqueConstraint("key", name=op.f("uq_workflow_templates_key")),
        schema="control",
    )
    op.create_table(
        "event_global_counter",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("last_position", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_event_global_counter_singleton")),
        sa.CheckConstraint(
            "last_position >= 0", name=op.f("ck_event_global_counter_position_nonnegative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_global_counter")),
        schema="event_store",
    )
    op.create_table(
        "configuration_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("configuration_id", sa.UUID(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(content_hash) = 64",
            name=op.f("ck_configuration_revisions_content_hash_length"),
        ),
        sa.CheckConstraint(
            "revision > 0", name=op.f("ck_configuration_revisions_revision_positive")
        ),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["control.configurations.id"],
            name=op.f("fk_configuration_revisions_configuration_id_configurations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_configuration_revisions")),
        sa.UniqueConstraint("configuration_id", "revision", name="uq_configuration_revision"),
        schema="control",
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','queued','active','waiting','completed','failed','blocked','cancelled')",
            name=op.f("ck_jobs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["control.projects.id"],
            name=op.f("fk_jobs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        schema="control",
    )
    op.create_table(
        "workflow_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_template_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("spec_version", sa.String(length=20), nullable=False),
        sa.Column("compiler_version", sa.String(length=40), nullable=False),
        sa.Column("spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("layout_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(content_hash) = 64", name=op.f("ck_workflow_versions_content_hash_length")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_workflow_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["workflow_template_id"],
            ["control.workflow_templates.id"],
            name=op.f("fk_workflow_versions_workflow_template_id_workflow_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_versions")),
        sa.UniqueConstraint("workflow_template_id", "version", name="uq_workflow_version"),
        schema="control",
    )
    op.create_table(
        "run_config_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workflow_version_id", sa.UUID(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column(
            "resolved_revisions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("effective_spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(snapshot_hash) = 64",
            name=op.f("ck_run_config_snapshots_snapshot_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["control.workflow_versions.id"],
            name=op.f("fk_run_config_snapshots_workflow_version_id_workflow_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_config_snapshots")),
        sa.UniqueConstraint("snapshot_hash", name=op.f("uq_run_config_snapshots_snapshot_hash")),
        schema="control",
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("run_number", sa.Integer(), nullable=False),
        sa.Column("parent_run_id", sa.UUID(), nullable=True),
        sa.Column("workflow_version_id", sa.UUID(), nullable=False),
        sa.Column("config_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("langgraph_thread_id", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("desired_state", sa.String(length=20), nullable=False),
        sa.Column("claimable_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_command_sequence", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "desired_state IN ('running','paused','cancelled')", name=op.f("ck_runs_desired_state")
        ),
        sa.CheckConstraint(
            "status IN ('queued','claiming','running','pause_requested','paused','approval_required','cancel_requested','completed','failed','blocked','cancelled')",
            name=op.f("ck_runs_status"),
        ),
        sa.CheckConstraint(
            "next_command_sequence >= 0", name=op.f("ck_runs_command_sequence_nonnegative")
        ),
        sa.CheckConstraint("run_number > 0", name=op.f("ck_runs_run_number_positive")),
        sa.ForeignKeyConstraint(
            ["config_snapshot_id"],
            ["control.run_config_snapshots.id"],
            name=op.f("fk_runs_config_snapshot_id_run_config_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["control.jobs.id"], name=op.f("fk_runs_job_id_jobs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["parent_run_id"],
            ["control.runs.id"],
            name=op.f("fk_runs_parent_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["control.workflow_versions.id"],
            name=op.f("fk_runs_workflow_version_id_workflow_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("job_id", "run_number", name="uq_runs_job_number"),
        sa.UniqueConstraint("langgraph_thread_id", name="uq_runs_langgraph_thread"),
        schema="control",
    )
    op.create_table(
        "retry_counters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("scope_key", sa.String(length=200), nullable=False),
        sa.Column("failure_class", sa.String(length=80), nullable=False),
        sa.Column("consumed", sa.Integer(), nullable=False),
        sa.Column("maximum", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint("consumed >= 0", name=op.f("ck_retry_counters_consumed_nonnegative")),
        sa.CheckConstraint("maximum >= 0", name=op.f("ck_retry_counters_maximum_nonnegative")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["control.runs.id"],
            name=op.f("fk_retry_counters_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retry_counters")),
        sa.UniqueConstraint("run_id", "scope_key", "failure_class", name="uq_retry_counter_scope"),
        schema="control",
    )
    op.create_table(
        "run_commands",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_run_version", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending','applying','applied','rejected','superseded')",
            name=op.f("ck_run_commands_status"),
        ),
        sa.CheckConstraint(
            "kind IN ('pause','resume','cancel','instruction','retry')",
            name=op.f("ck_run_commands_kind"),
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_run_commands_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["control.runs.id"],
            name=op.f("fk_run_commands_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_commands")),
        sa.UniqueConstraint("run_id", "idempotency_key", name="uq_run_command_idempotency"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_run_command_sequence"),
        schema="control",
    )
    op.create_table(
        "run_leases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("owner_instance_id", sa.String(length=160), nullable=False),
        sa.Column("generation", sa.BigInteger(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("generation > 0", name=op.f("ck_run_leases_generation_positive")),
        sa.ForeignKeyConstraint(
            ["owner_instance_id"],
            ["control.orchestrator_instances.id"],
            name=op.f("fk_run_leases_owner_instance_id_orchestrator_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["control.runs.id"],
            name=op.f("fk_run_leases_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_leases")),
        sa.UniqueConstraint("run_id", "generation", name="uq_run_lease_generation"),
        schema="control",
    )
    op.create_index(
        "uq_run_leases_active",
        "run_leases",
        ["run_id"],
        unique=True,
        schema="control",
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column(
            "acceptance_criteria_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("verification_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','ready','running','waiting','approval_required','succeeded','failed','blocked','cancelled','skipped')",
            name=op.f("ck_tasks_status"),
        ),
        sa.CheckConstraint("weight > 0", name=op.f("ck_tasks_weight_positive")),
        sa.ForeignKeyConstraint(
            ["run_id"], ["control.runs.id"], name=op.f("fk_tasks_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("run_id", "id", name="uq_tasks_run_id_id"),
        sa.UniqueConstraint("run_id", "key", name="uq_tasks_run_key"),
        schema="control",
    )
    op.create_table(
        "events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("global_position", sa.BigInteger(), nullable=False),
        sa.Column("run_sequence", sa.BigInteger(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("type", sa.String(length=160), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=1024), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("task_attempt_id", sa.UUID(), nullable=True),
        sa.Column("workflow_node_id", sa.String(length=80), nullable=True),
        sa.Column("node_execution_id", sa.UUID(), nullable=True),
        sa.Column("source_kind", sa.String(length=80), nullable=False),
        sa.Column("source_name", sa.String(length=120), nullable=False),
        sa.Column("source_instance_id", sa.String(length=160), nullable=True),
        sa.Column("source_host_id", sa.String(length=160), nullable=True),
        sa.Column("source_sequence", sa.BigInteger(), nullable=True),
        sa.Column("source_dedupe_key", sa.String(length=600), nullable=True),
        sa.Column("correlation_id", sa.String(length=200), nullable=False),
        sa.Column("causation_event_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("idempotency_scope_key", sa.String(length=500), nullable=True),
        sa.Column("trace_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("data_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_refs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(run_id IS NULL AND run_sequence IS NULL) OR (run_id IS NOT NULL AND run_sequence IS NOT NULL)",
            name=op.f("ck_events_run_sequence_scope"),
        ),
        sa.CheckConstraint(
            "category IN ('auth','config','thread','job','run','graph','node','task','worker','model','tool','file','command','test','review','git','approval','artifact','failure','system')",
            name=op.f("ck_events_category"),
        ),
        sa.CheckConstraint("global_position > 0", name=op.f("ck_events_global_position_positive")),
        sa.CheckConstraint("mode IN ('real','demo')", name=op.f("ck_events_mode")),
        sa.CheckConstraint(
            "run_sequence IS NULL OR run_sequence > 0", name=op.f("ck_events_run_sequence_positive")
        ),
        sa.CheckConstraint(
            "severity IN ('debug','info','success','warning','error','critical')",
            name=op.f("ck_events_severity"),
        ),
        sa.CheckConstraint(
            "visibility IN ('owner','operator','internal')",
            name=op.f("ck_events_visibility"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["control.runs.id"], name=op.f("fk_events_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("global_position", name=op.f("pk_events")),
        sa.UniqueConstraint("event_id", name="uq_events_event_id"),
        sa.UniqueConstraint("idempotency_scope_key", name="uq_events_idempotency_scope_key"),
        sa.UniqueConstraint("source_dedupe_key", name="uq_events_source_dedupe_key"),
        schema="event_store",
    )
    op.create_index(
        "ix_events_category_type",
        "events",
        ["category", "type"],
        unique=False,
        schema="event_store",
    )
    op.create_index(
        "ix_events_run_recorded",
        "events",
        ["run_id", "recorded_at"],
        unique=False,
        schema="event_store",
    )
    op.create_index(
        "uq_events_run_sequence",
        "events",
        ["run_id", "run_sequence"],
        unique=True,
        schema="event_store",
        postgresql_where=sa.text("run_id IS NOT NULL"),
    )
    op.create_table(
        "run_event_counters",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("last_sequence", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "last_sequence >= 0", name=op.f("ck_run_event_counters_sequence_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["control.runs.id"],
            name=op.f("fk_run_event_counters_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_run_event_counters")),
        schema="event_store",
    )
    op.create_table(
        "task_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("worker_revision_id", sa.UUID(), nullable=True),
        sa.Column("base_sha", sa.String(length=64), nullable=True),
        sa.Column("result_sha", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','verifying','reviewing','succeeded','failed','cancelled','unknown')",
            name=op.f("ck_task_attempts_status"),
        ),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_task_attempts_attempt_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["control.tasks.id"],
            name=op.f("fk_task_attempts_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_attempts")),
        sa.UniqueConstraint("task_id", "attempt_number", name="uq_task_attempt_number"),
        schema="control",
    )
    op.create_table(
        "task_dependencies",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_task_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "task_id <> depends_on_task_id", name=op.f("ck_task_dependencies_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "depends_on_task_id"],
            ["control.tasks.run_id", "control.tasks.id"],
            name="fk_task_dependencies_depends_on",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "task_id"],
            ["control.tasks.run_id", "control.tasks.id"],
            name="fk_task_dependencies_task",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "run_id", "task_id", "depends_on_task_id", name=op.f("pk_task_dependencies")
        ),
        schema="control",
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("task_attempt_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=120), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=200), nullable=False),
        sa.Column("redaction_classification", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "redaction_classification IN ('public','owner','sensitive','redacted')",
            name=op.f("ck_artifacts_redaction_classification"),
        ),
        sa.CheckConstraint("char_length(sha256) = 64", name=op.f("ck_artifacts_sha256_length")),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_artifacts_size_nonnegative")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["control.runs.id"],
            name=op.f("fk_artifacts_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["control.task_attempts.id"],
            name=op.f("fk_artifacts_task_attempt_id_task_attempts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_artifacts_storage_key")),
        schema="control",
    )
    op.create_table(
        "node_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("task_attempt_id", sa.UUID(), nullable=True),
        sa.Column("workflow_node_id", sa.String(length=80), nullable=False),
        sa.Column("execution_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("input_summary", sa.String(length=1024), nullable=True),
        sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','waiting','interrupted','succeeded','failed','cancelled','skipped')",
            name=op.f("ck_node_executions_status"),
        ),
        sa.CheckConstraint(
            "execution_number > 0", name=op.f("ck_node_executions_execution_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["control.runs.id"],
            name=op.f("fk_node_executions_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["control.task_attempts.id"],
            name=op.f("fk_node_executions_task_attempt_id_task_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["control.tasks.id"],
            name=op.f("fk_node_executions_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_executions")),
        sa.UniqueConstraint(
            "run_id", "workflow_node_id", "execution_number", name="uq_node_execution_number"
        ),
        schema="control",
    )
    op.create_table(
        "effects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("task_attempt_id", sa.UUID(), nullable=True),
        sa.Column("node_execution_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("request_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("fence_generation", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.String(length=240), nullable=True),
        sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "status IN ('prepared','dispatched','running','succeeded','failed','cancel_requested','cancelled','unknown')",
            name=op.f("ck_effects_status"),
        ),
        sa.CheckConstraint(
            "fence_generation > 0", name=op.f("ck_effects_fence_generation_positive")
        ),
        sa.ForeignKeyConstraint(
            ["node_execution_id"],
            ["control.node_executions.id"],
            name=op.f("fk_effects_node_execution_id_node_executions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["control.runs.id"],
            name=op.f("fk_effects_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["control.task_attempts.id"],
            name=op.f("fk_effects_task_attempt_id_task_attempts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_effects")),
        sa.UniqueConstraint("run_id", "idempotency_key", name="uq_effect_run_idempotency"),
        schema="control",
    )
    op.create_table(
        "failures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("task_attempt_id", sa.UUID(), nullable=True),
        sa.Column("node_execution_id", sa.UUID(), nullable=True),
        sa.Column("failure_class", sa.String(length=80), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("budget_scope", sa.String(length=120), nullable=False),
        sa.Column("consumes_semantic_attempt", sa.Boolean(), nullable=False),
        sa.Column("summary", sa.String(length=1024), nullable=False),
        sa.Column("detail_artifact_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_execution_id"],
            ["control.node_executions.id"],
            name=op.f("fk_failures_node_execution_id_node_executions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["control.runs.id"],
            name=op.f("fk_failures_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["control.task_attempts.id"],
            name=op.f("fk_failures_task_attempt_id_task_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["control.tasks.id"],
            name=op.f("fk_failures_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_failures")),
        schema="control",
    )
    op.create_foreign_key(
        "fk_configurations_current_revision",
        "configurations",
        "configuration_revisions",
        ["current_revision_id"],
        ["id"],
        source_schema="control",
        referent_schema="control",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_workflow_templates_current_published_version",
        "workflow_templates",
        "workflow_versions",
        ["current_published_version_id"],
        ["id"],
        source_schema="control",
        referent_schema="control",
        ondelete="RESTRICT",
    )
    op.execute("INSERT INTO event_store.event_global_counter (id, last_position) VALUES (1, 0)")
    op.execute(
        """
        CREATE FUNCTION event_store.reject_event_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $body$
        BEGIN
          RAISE EXCEPTION 'event rows are append-only' USING ERRCODE = '55000';
        END
        $body$
        """
    )
    op.execute(
        """
        CREATE TRIGGER events_append_only
        BEFORE UPDATE OR DELETE ON event_store.events
        FOR EACH ROW EXECUTE FUNCTION event_store.reject_event_mutation()
        """
    )
    op.execute(
        """
        CREATE FUNCTION control.reject_immutable_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $body$
        BEGIN
          RAISE EXCEPTION 'immutable revision or snapshot cannot be changed'
            USING ERRCODE = '55000';
        END
        $body$
        """
    )
    for table in ("configuration_revisions", "run_config_snapshots"):
        op.execute(
            f"""
            CREATE TRIGGER {table}_immutable
            BEFORE UPDATE OR DELETE ON control.{table}
            FOR EACH ROW EXECUTE FUNCTION control.reject_immutable_mutation()
            """
        )
    op.execute(
        """
        CREATE FUNCTION control.reject_published_workflow_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $body$
        BEGIN
          IF OLD.published_at IS NOT NULL THEN
            RAISE EXCEPTION 'published workflow versions are immutable' USING ERRCODE = '55000';
          END IF;
          RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END
        $body$
        """
    )
    op.execute(
        """
        CREATE TRIGGER workflow_versions_published_immutable
        BEFORE UPDATE OR DELETE ON control.workflow_versions
        FOR EACH ROW EXECUTE FUNCTION control.reject_published_workflow_mutation()
        """
    )

    op.execute(
        "GRANT USAGE ON SCHEMA control, event_store, langgraph TO "
        "jarvis_v1_api, jarvis_v1_orchestrator, jarvis_v1_readonly"
    )
    op.execute("GRANT CREATE ON SCHEMA langgraph TO jarvis_v1_migrator")
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA langgraph "
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO jarvis_v1_orchestrator"
    )
    op.execute("GRANT SELECT ON ALL TABLES IN SCHEMA control TO jarvis_v1_readonly")
    op.execute("GRANT SELECT ON event_store.events TO jarvis_v1_readonly")
    op.execute(
        "GRANT SELECT ON ALL TABLES IN SCHEMA control TO jarvis_v1_api, jarvis_v1_orchestrator"
    )
    op.execute(
        "GRANT INSERT, UPDATE ON control.projects, control.jobs, control.runs, "
        "control.run_commands, control.idempotency_records TO jarvis_v1_api"
    )
    op.execute(
        "GRANT INSERT, UPDATE ON control.jobs, control.runs, control.tasks, "
        "control.task_dependencies, control.task_attempts, control.node_executions, "
        "control.run_commands, control.idempotency_records, control.orchestrator_instances, "
        "control.run_leases, control.effects, control.failures, control.retry_counters, "
        "control.artifacts TO jarvis_v1_orchestrator"
    )
    op.execute(
        "GRANT SELECT, INSERT ON event_store.events TO jarvis_v1_api, jarvis_v1_orchestrator"
    )
    op.execute(
        "GRANT SELECT, INSERT, UPDATE ON event_store.event_global_counter, "
        "event_store.run_event_counters TO jarvis_v1_api, jarvis_v1_orchestrator"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE control.workflow_templates "
        "DROP CONSTRAINT IF EXISTS fk_workflow_templates_current_published_version"
    )
    op.execute(
        "ALTER TABLE control.configurations "
        "DROP CONSTRAINT IF EXISTS fk_configurations_current_revision"
    )
    op.drop_table("failures", schema="control")
    op.drop_table("effects", schema="control")
    op.drop_table("node_executions", schema="control")
    op.drop_table("artifacts", schema="control")
    op.drop_table("task_dependencies", schema="control")
    op.drop_table("task_attempts", schema="control")
    op.drop_table("run_event_counters", schema="event_store")
    op.drop_index(
        "uq_events_run_sequence",
        table_name="events",
        schema="event_store",
        postgresql_where=sa.text("run_id IS NOT NULL"),
    )
    op.drop_index("ix_events_run_recorded", table_name="events", schema="event_store")
    op.drop_index("ix_events_category_type", table_name="events", schema="event_store")
    op.drop_table("events", schema="event_store")
    op.drop_table("tasks", schema="control")
    op.drop_index(
        "uq_run_leases_active",
        table_name="run_leases",
        schema="control",
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_table("run_leases", schema="control")
    op.drop_table("run_commands", schema="control")
    op.drop_table("retry_counters", schema="control")
    op.drop_table("runs", schema="control")
    op.drop_table("run_config_snapshots", schema="control")
    op.drop_table("workflow_versions", schema="control")
    op.drop_table("jobs", schema="control")
    op.drop_table("configuration_revisions", schema="control")
    op.drop_table("event_global_counter", schema="event_store")
    op.drop_table("workflow_templates", schema="control")
    op.drop_table("projects", schema="control")
    op.drop_table("orchestrator_instances", schema="control")
    op.drop_table("idempotency_records", schema="control")
    op.drop_table("configurations", schema="control")
    op.execute("DROP FUNCTION control.reject_published_workflow_mutation()")
    op.execute("DROP FUNCTION control.reject_immutable_mutation()")
    op.execute("DROP FUNCTION event_store.reject_event_mutation()")
    op.execute("DROP SCHEMA event_store")
    op.execute("DROP SCHEMA control")
    # The LangGraph-owned schema is retained so application rollback never
    # destroys checkpoint tables created by the checkpointer package.
    # ### end Alembic commands ###
